### PR TITLE
Milestone 5 frienships v1

### PR DESCRIPTION
**Pull request by daviidy**
We created a model with associations and all requested features for friendships.
We added also unit tests

### CODE REVIEW

**Review by SpaYco — CHANGES_REQUESTED** [review]
# Changes Requested 

Hello Team! <span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_32.png);background-position:28.025851938895418% 81.96239717978848%;background-size:5418.75% 5418.75%" data-codepoints="1f44b"></span></span> 
Awesome job so far!! <span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_32.png);background-position:30.0235017626322% 4.054054054054054%;background-size:5418.75% 5418.75%" data-codepoints="1f44d"></span></span> you still need to make some changes though! 

## Required Changes <span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_32.png);background-position:95.94594594594594% 53.99529964747356%;background-size:5418.75% 5418.75%" data-codepoints="267b-fe0f"></span></span> 

- [x] User model should have: `has_many :inverted_friendships, class_name: "Friendship", foreign_key: "friend_id"` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friend.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)) (friendship = follower)
- [x] please add tests for what you've added in this milestone ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

## Optional 🟢 

- [x] can you please change `followers` to `friendships` for less confusion?

### please make the appropriate changes and ask for another code review <span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_32.png);background-position:97.94359576968273% 95.94594594594594%;background-size:5418.75% 5418.75%" data-codepoints="2714-fe0f"></span></span> 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Required :recycle: 
#### Hey there :wave: 
Well done in making changes requested by the previous reviewer.
However, there are still some changes to be made.
- [ ] There is an error in your unit test. When I tried to run RSpec I was getting some errors and that is because you did not set up your unit test correctly. Please go back and update your test accocrdingly.
#### Do request another review when you are done making the changes.

slack(@ebeagusamuel)

**Comment by daviidy** [comment]
The changes have been done @ebeagusamuel
Thank you

**Review by peterrobert — APPROVED** [review]
### APPROVED 👍🏿 💯 
Hello, @daviidy  great work making the changes as requested by the previous TSE. Your project is good to go. 

### On to the next milestone and happy coding 💻

**Pull request merged**
