### PR TITLE
Milestone 6 frienships v2

### PR DESCRIPTION
**Pull request by daviidy**
We updated the friendships controller for stopping reverse pairs.
We added a `set_friendships` method for checking if a friend request has been already made
```
def set_friendship
    @friendship = Friendship.find_by(user_id: params[:user_id], friend_id: current_user.id) ||
                  Friendship.find_by(user_id: current_user.id, friend_id: params[:user_id])
  end
```
User can accept or refuse an invitation. You can see that on the friends page
User can only see his posts and the posts of his friends in the timeline page
2020-12-18 13_43_11-RorSocialScaffold

### CODE REVIEW

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status: require changes :recycle: 

Hi @team nice job so far :clap: :clap: :clap: :clap:, it seems like you didn't work on the main requirements, due to that you have some changes :hammer: :wrench: :hammer_and_wrench: :toolbox: to take care of.

Please check the comments below
:point_down: :point_down: :point_down: :point_down:.

## Required Changes:

- [ ] When requesting a friendship, it should not be completed, the other user should accept it or refuse it.

- [ ] PostsController#index displays posts in a timeline (their own posts + posts from their friends) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/timeline.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project))

- [ ] Please add more tests these ones are not enough, don't forget to add integration tests with Capybara.

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat: 
_If you have a question or need any kind of help don't hesitate to contact me on slack._

**Comment by daviidy** [comment]
@elmejdki thanks for your review. You said
`When requesting a friendship, it should not be completed, the other user should accept it or refuse it.`
But I've done that, user can accept or refuse an invitation
` PostsController#index displays posts in a timeline (their own posts + posts from their friends) (screenshot from Odin Project)`
I've done that also, so I really don't know what you're talking about exactly

**Comment by daviidy** [comment]
User can accept or refuse an invitation. You can see that on the friends page
User can only see his posts and the posts of his friends in the timeline page

2020-12-18 13_43_11-RorSocialScaffold

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far, everything works fine, but there are a few more things required. 
### General

- [ ] Lets test all components in the project .
- [ ]  Instead of processing objects in application memory, let's define association with SQL query.
````ruby
# confirm friends
has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships

# pending_friends
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend

#friend_requests
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships

`````

### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Review by BrittanyBlake — CHANGES_REQUESTED** [review]
### Status: Changes Required ♻️ 
****
### Hi @daviidy and @AkintoyeOlamide! 👋 
You have done a great job implementing the changes requested by the previous TSE! 👍 You have also done a wonderful job with your project so far! It looks really good! 👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

- [ ] Two of your Rspec tests are failing. Please address the issues and resubmit 👇🏾 
Screen Shot 2020-12-19 at 10 34 53 AM


****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

**Comment by daviidy** [comment]
Thanks, @BrittanyBlake. It's done

**Review by BrittanyBlake — APPROVED** [review]
### Status: Approved ✅ 
****
### Hi Team! 👋 
### Great job implementing the requested changes!! 🎖️ It's a 👍 from me! Go ahead and merge this pull request and keep up the good work 😄
****

 Good Luck and Happy Coding! 🍀 👩🏾‍💻

**Pull request merged**
